In [1]:
#Functional Programming
items = [1,2,3,4,5]
def inc(x): 
    return x+1

list(map(inc,items))

[2, 3, 4, 5, 6]

In [2]:
#Python allows you to define the function directly within the first argument using lambda as a function. 
#This greatly reduces the code and compacts the previous construct into a single line of code
list(map((lambda x: x+1),items))

[2, 3, 4, 5, 6]

In [3]:
#The filter() function extracts the elements of the list for which the function returns True
list(filter((lambda x: x < 4), items))

[1, 2, 3]

In [4]:
#The reduce() function instead considers all the elements of the list to produce a single result
print(items)
from functools import reduce
reduce((lambda x,y: x+y), items)

[1, 2, 3, 4, 5]


15

In [5]:
S = [x**2 for x in range(5)]
S

[0, 1, 4, 9, 16]

In [ ]:
#The NumPy is a basic package for scientific computing with Python and especially for dat a analysis
#In fact, this library is the basis of a large amount of mathematical and scientific Python packages

In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#Ndarray : The Heart of the Library
#ndarray (which stands for N-dimensional array). 

In [6]:
#The easiest way to define a new ndarray is to use the array() function
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
type(a) #You can easily check that a newly created object is an ndarray by passing the new variable to the type() function.

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [9]:
print(a.ndim)
print(a.size)
print(a.shape)

1
3
(3,)


In [10]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [11]:
print(b.dtype)
print(b.ndim)
print(b.size)
print(b.shape)

float64
2
4
(2, 2)


In [12]:
c = np.array([[1, 2, 3],[4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#The array() function, in addition to lists, can accept tuples and sequences of tuples.
d = np.array(((1, 2, 3),(4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#The array() function, in addition to lists, can accept tuples
d = np.array(((1, 2, 3),(4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#It can also accept sequences of tuples and interconnected lists .
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#NumPy arrays are designed to contain a wide variety of data types
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [19]:
a=np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
b=np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
c=np.arange(0, 10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
d=np.arange(4, 10)
d

array([4, 5, 6, 7, 8, 9])

In [23]:
e=np.arange(0, 12, 3)
e

array([0, 3, 6, 9])

In [24]:
f=np.arange(0, 6, 0.6)
f

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [25]:
g=np.arange(0, 12).reshape(3, 4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
#using random() function of the numpy.random module
k=np.random.random(3)
k

array([0.81766685, 0.39283206, 0.02289612])

In [27]:
d=np.random.random((3,3))
d

array([[0.5723164 , 0.94016624, 0.1355511 ],
       [0.353708  , 0.83323958, 0.37998092],
       [0.56274478, 0.76206793, 0.68153667]])

In [28]:
#Basic Operations
a = np.arange(4)
a+4

array([4, 5, 6, 7])

In [29]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [30]:
print(a)
print(b)
#Element-wise addition
a+b

[0 1 2 3]
[4 5 6 7]


array([ 4,  6,  8, 10])

In [31]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [34]:
a = np.arange(4)
print(a)
print(a+1)

[0 1 2 3]
[1 2 3 4]


In [35]:
a = np.arange(1, 5)
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [36]:
#Aggregate Functions
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

15.0
0.3
5.7
3.0
2.0079840636817816


In [37]:
#Indexing, Slicing, and Iterating
a = np.arange(10, 16)
print(a)
print(a[4])
print(a[-6])

[10 11 12 13 14 15]
14
10


In [38]:
#select multiple items at once
a[[1, 3, 4]]

array([11, 13, 14])

In [39]:
A = np.arange(10, 19).reshape((3, 3))
print(A)
print("---------")
A[1, 2]=7
print(A)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
---------
[[10 11 12]
 [13 14  7]
 [16 17 18]]


In [40]:
#slicing
a = np.arange(10, 16)
print(a)
print(a[1:5])
print(a[1:5:2])

[10 11 12 13 14 15]
[11 12 13 14]
[11 13]


In [41]:
#In the case of a two-dimensional array,
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [42]:
A[0,:]

array([10, 11, 12])

In [43]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [44]:
#Iterating an Array
for i in A:
    print(i)

[10 11 12]
[13 14 15]
[16 17 18]


In [45]:
#If you want to make an iteration element by element
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [46]:
print(A)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [47]:
np.apply_along_axis(np.mean, axis=0, arr=A) #By column

array([13., 14., 15.])

In [48]:
np.apply_along_axis(np.mean, axis=1, arr=A) #By rows

array([11., 14., 17.])

In [49]:
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [50]:
#Conditions and Boolean Arrays
A = np.random.random((4, 4))
A

array([[0.99032338, 0.9249047 , 0.44322904, 0.72361584],
       [0.54518336, 0.85933709, 0.43603046, 0.14060138],
       [0.85281176, 0.08416282, 0.9021835 , 0.83636408],
       [0.22811843, 0.7096592 , 0.62141519, 0.52568722]])

In [51]:
A < 0.5

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True, False, False, False]])

In [52]:
A[A < 0.5]

array([0.44322904, 0.43603046, 0.14060138, 0.08416282, 0.22811843])