In [2]:
#Shape Manipulation
#You already saw, during the creation of a two-dimensional array, 
#how it is possible to convert a one-dimensional array into a matrix, thanks to the reshape() f unction.
import numpy as np
a = np.random.random(12)
a

array([0.26493464, 0.63268038, 0.6537077 , 0.8635542 , 0.83851867,
       0.2802184 , 0.03007458, 0.42728387, 0.12542181, 0.42883284,
       0.48003899, 0.46655328])

In [3]:
A = a.reshape(3, 4)
A

array([[0.26493464, 0.63268038, 0.6537077 , 0.8635542 ],
       [0.83851867, 0.2802184 , 0.03007458, 0.42728387],
       [0.12542181, 0.42883284, 0.48003899, 0.46655328]])

In [4]:
#The reshape() function returns a new array and can therefore create new objects. 
#However if you want to modify the object by modifying the shape, you have to assign a tuple containing the new 
#dimensions directly to its shape att ribute.
a.shape = (3, 4)
a

array([[0.26493464, 0.63268038, 0.6537077 , 0.8635542 ],
       [0.83851867, 0.2802184 , 0.03007458, 0.42728387],
       [0.12542181, 0.42883284, 0.48003899, 0.46655328]])

In [5]:
#The inverse operation is also possible, that is, you can convert a two-dimensional array into 
#a one-dimensional array, by using the ravel() function.
a = a.ravel()
a

array([0.26493464, 0.63268038, 0.6537077 , 0.8635542 , 0.83851867,
       0.2802184 , 0.03007458, 0.42728387, 0.12542181, 0.42883284,
       0.48003899, 0.46655328])

In [6]:
#Or even here acting directly on the shape attribute of the array itself.
a.shape = (3, 4)
print(a)
a.shape = (12)
a

[[0.26493464 0.63268038 0.6537077  0.8635542 ]
 [0.83851867 0.2802184  0.03007458 0.42728387]
 [0.12542181 0.42883284 0.48003899 0.46655328]]


array([0.26493464, 0.63268038, 0.6537077 , 0.8635542 , 0.83851867,
       0.2802184 , 0.03007458, 0.42728387, 0.12542181, 0.42883284,
       0.48003899, 0.46655328])

In [9]:
#Another important operation is transposing a matrix, which is inverting the columns with the rows.
print(A)
A.transpose()

[[0.26493464 0.63268038 0.6537077  0.8635542 ]
 [0.83851867 0.2802184  0.03007458 0.42728387]
 [0.12542181 0.42883284 0.48003899 0.46655328]]


array([[0.26493464, 0.83851867, 0.12542181],
       [0.63268038, 0.2802184 , 0.42883284],
       [0.6537077 , 0.03007458, 0.48003899],
       [0.8635542 , 0.42728387, 0.46655328]])

In [10]:
#Joining Arrays
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [14]:
#General Concepts (copies or views)
#If you assign one array a to another array b, you are not copying it; array b is just another way to call array a. 
a = np.array([1, 2, 3, 4]) 
b = a
b

array([1, 2, 3, 4])

In [13]:
a[2] = 0
b

array([1, 2, 0, 4])

In [15]:
#Even When you slice an array, the object returned is a view of the original array
c = a[0:2]
c

array([1, 2])

In [17]:
a[0] = 0
c
#As you can see, even when slicing, you are actually pointing to the same object

array([0, 2])

In [18]:
#If you want to generate a complete and distinct array, use the copy() function
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [19]:
a[0] = 0
print(c)

[1 2 3 4]


In [20]:
#Vectorization
A = np.array([1, 2, 3, 4])
B = np.array([1, 2, 3, 4])
C = A * B
C

#In other programming language, to do that you need to have a complex code
#in case one dimentional array
for (i = 0; i < rows; i++){
  c[i] = a[i]*b[i];
}
#Two dimensional arrays
for( i=0; i < rows; i++){
   for(j=0; j < columns; j++){
      c[i][j] = a[i][j]*b[i][j];
   }
}

array([ 1,  4,  9, 16])

In [4]:
import numpy as np
#Reading and Writing Array Data on Files
data=([[ 0.86466285,  0.76943895,  0.22678279],
       [ 0.12452825,  0.54751384,  0.06499123],
       [ 0.06216566,  0.85045125,  0.92093862],
       [ 0.58401239,  0.93455057,  0.28972379]])
np.save('saved_data',data)

In [5]:
loaded_data = np.load('saved_data.npy')
loaded_data

array([[0.86466285, 0.76943895, 0.22678279],
       [0.12452825, 0.54751384, 0.06499123],
       [0.06216566, 0.85045125, 0.92093862],
       [0.58401239, 0.93455057, 0.28972379]])

In [6]:
data = np.genfromtxt('ch3_data.csv', delimiter=',', names=True)
data

array([(1., 123., 1.4, 23.), (2., 110., 0.5, 18.), (3., 164., 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value2_1', '<f8')])

In [7]:
data = np.genfromtxt('ch3_data.csv', delimiter=',')
data

array([[  nan,   nan,   nan,   nan],
       [  1. , 123. ,   1.4,  23. ],
       [  2. , 110. ,   0.5,  18. ],
       [  3. , 164. ,   2.1,  19. ]])

In [24]:
#In case you have in the file blank values (nan values)
data2 = np.genfromtxt('ch3_data2.csv', delimiter=',', names=True)
data2

array([(1., 123., 1.4, 23.), (2., 110., nan, 18.), (3.,  nan, 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value2_1', '<f8')])

In [25]:
data2['id']

array([1., 2., 3.])

In [26]:
data2[0]

(1., 123., 1.4, 23.)