### Please submit a Jupyter Notebook file for your answers to the following Five questions

##### Q1 (3 points): Write a code to create a Pandas dataframe from the following dictionary with the labels below and select the rows in the dataframe where the score is missing, i.e. is NaN 

In [55]:
import pandas as pd
import numpy as np

In [56]:
exam_data= {'name':['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'],
             'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],}

labels = ['a','b','c','d','e','f','g','h','i','j']

df_exam_data = pd.DataFrame(exam_data, index=labels)
print('Rows where score is missing:')
df_exam_data[df_exam_data['score'].isna()]

Rows where score is missing:


name  score
d  James    NaN
h  Laura    NaN

### Q2 (8 points): Write a Python code to do the following:


#####  A) Read data from students.csv file (the file is available in Blackboard) into a Pandas data frame named csvframe and compute the average of student’s grades. The code should display the names of each student with the mean of his/her average as follow:

In [57]:
students_data = pd.read_csv("students.csv")
students_data

Test  Steven Wiliam  Ersula Austin  Jesse Brandon
0  Test1             80             85             90
1  Test2             70             95             80
2  Test3             80             75             85

In [78]:
students_data_mean = students_data[['Steven Wiliam','Ersula Austin','Jesse Brandon']].mean()
student_mean= pd.Series(students_data_mean)
df_student_mean = student_mean.to_frame()
df_student_mean = df_student_mean.rename(columns = {0:'Average'})
df_student_mean = df_student_mean.rename_axis('Student Name', axis=1)
df_student_mean


Student Name     Average
Steven Wiliam  76.666667
Ersula Austin  85.000000
Jesse Brandon  85.000000

##### B.) Add the following new student information to the dataframe and display the content of the dataframe after addition

In [59]:
new_students_data = students_data.assign(JamesWilliam=[90, 90, 90,])
new_students_data.rename(columns={"JamesWilliam" : "James William"}, inplace=True)
new_students_data

Test  Steven Wiliam  Ersula Austin  Jesse Brandon  James William
0  Test1             80             85             90             90
1  Test2             70             95             80             90
2  Test3             80             75             85             90

##### C.) Write a code to delete "Steven Wiliam" column and display the dataframe after deletion

In [60]:
dropped_data = new_students_data.drop(['Steven Wiliam'], axis=1)
dropped_data

Test  Ersula Austin  Jesse Brandon  James William
0  Test1             85             90             90
1  Test2             95             80             90
2  Test3             75             85             90

##### D) Write a code to update Test 2 grade of "Jesse Brandon" to 90 and show the content after updating

In [61]:
dropped_data['Jesse Brandon'] = dropped_data['Jesse Brandon'].replace([80], 90)
dropped_data

Test  Ersula Austin  Jesse Brandon  James William
0  Test1             85             90             90
1  Test2             95             90             90
2  Test3             75             85             90

### Q3 (3 points): Write a Python program to read the data from students2.csv file (the file is available in Blackboard) into data frame named csvframe2 and replace the missing values by the mean of the columns. Please see below the contents before and after the missing value imputation:

Data Before:

In [62]:
csvframe2 = pd.read_csv("students2.csv")
csvframe2

Name  Test1  Test2  Test3
0  Steven Wiliam   80.0   85.0   90.0
1  Ersula Austin    NaN   95.0    NaN
2  Jesse Brandon   80.0    NaN   85.0

Data After:

In [63]:
csvframe2[['Test1', 'Test2','Test3']] = csvframe2[['Test1', 'Test2', 'Test3']].fillna(csvframe2[['Test1', 'Test2', 'Test3']].mean())
csvframe2

Name  Test1  Test2  Test3
0  Steven Wiliam   80.0   85.0   90.0
1  Ersula Austin   80.0   95.0   87.5
2  Jesse Brandon   80.0   90.0   85.0

### Q4 (6 points): Write a code to read the data from students3.csv file (the file is available in Blackboard) into a Pandas dataframe named csvframe3 and then iterate the contents in the dataframe (using a loop) and display the first name and last name for students as follow: 

##### Note: len(dataframe) could be used to get the number of rows in the dataframe.

In [64]:
csvframe3 = pd.read_csv("students3.csv")
csvframe3

Name  Test1  Test2  Test3
0  Steven Wiliam     80     85     90
1  Ersula Austin     70     95     80
2  Jesse Brandon     80     75     85

In [65]:
csvframe3[['Fname', 'Lname']] = csvframe3['Name'].str.split(' ', 1, expand = True)
for names in range(0, len(csvframe3)):
    print(f"The first name of the {names+1} student is: {csvframe3.loc[names,'Fname']} and the last name is: {csvframe3.loc[names,'Lname']}")

The first name of the 1 student is: Steven and the last name is: Wiliam
The first name of the 2 student is: Ersula and the last name is: Austin
The first name of the 3 student is: Jesse and the last name is: Brandon


### Q5 (5 points): In this question, you need to use diabetes Dataset and write a python code to predict the patients' progress after a year. You need to get 42 patients for testing and the rest for Training. Also, please note that you need to randomly shuffle the dataset using permutation.

In [66]:
from sklearn import datasets
from sklearn import linear_model

In [67]:
diabetes = datasets.load_diabetes()
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [68]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [69]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [70]:
np.random.seed(0)
diabetes = datasets.load_diabetes()
x = diabetes.data
y = diabetes.target
i = np.random.permutation(len(diabetes.data))
print(i)
x_train = x[i[:-42]]
y_train = y[i[:-42]]
x_test = x[i[-42:]]
y_test = y[i[-42:]]

[362 249 271 435 400 403  12 399 198 205  78 144 298 171 268  21 194   1
  10 208  76  37 388 411 289 100 261 401 319 206 375 283 373 344 287 360
 179 238 434 302 158 118 339 397 330 296 164  54 157  71 284   6 343 326
 159  15 320  60 282 142  56 124 107 132 382 102 160 141 186 441  90  59
 347 233 427  65 438 155 122 276 188  96 170 113 381 213 134  49  52  74
  26  45 389 154   4 386 225 327 264   8 190   5 371 200 313   7 325 366
  22  68 437  20 353 281  14 300 240 175 405 153  75  64  55 135 329  81
 316 369 328 414 421 361 415 232 224 252 254 418 106 278  63 336 378 387
 430  89  93 245 272 241  92  18 145 150 322 393 297 231  66 380 412 140
 101 345 247 363  17 146 315 220  30 114 235 103 219 274 176 191 116 168
 367 120 218 112 303 136 308 221 126 196 332 424 133  33 419 162  34  44
  97  85  61 167 199 173 229 236 433 376 250 108 407  46 357 372 263  73
 137 422 246 253  29 181 374 301  51 365 391 217 432  27   2 259 156 255
 417 346 138 212 104 310 306 311 215 348 189 214  3

In [71]:
linreg = linear_model.LinearRegression()
linreg.fit(x_train,y_train)

LinearRegression()

In [72]:
linreg.coef_

array([  -5.10122558, -235.60518272,  521.43329862,  336.24078496,
       -977.25339722,  615.575888  ,  190.22736464,  211.46526111,
        756.40504118,   87.65646967])

In [73]:
linreg.predict(x_test)

array([166.04062991, 150.20480103, 227.73065852, 199.37481936,
       152.41759898, 219.26172956, 137.91649695, 120.52639408,
        87.51536744, 191.84522348, 102.92351649, 183.97802142,
       201.5218887 , 131.21032377, 135.24352953, 182.84560588,
       145.86441679,  79.32267787, 176.29534337, 163.18823264,
       164.20215583, 257.85667027, 135.3567176 , 138.12226923,
       174.87098891,  64.65037972,  83.46174085,  77.52098753,
       150.34393584,  95.28118828,  86.81446046, 118.69618463,
       175.63772825, 207.87928597, 176.92466888, 170.21621404,
       271.26492461, 205.88915139,  91.35666337, 233.5424582 ,
       107.89125159, 219.08821476])

In [74]:
y_test

array([242., 168., 128., 233., 209., 225.,  83., 214.,  96., 129.,  47.,
       229., 293.,  74., 202., 164., 202.,  59.,  91., 120., 151., 310.,
        90., 116., 147.,  43.,  42.,  48., 134.,  84.,  71.,  64.,  70.,
       310., 311., 122., 243., 248.,  91., 281., 142., 295.])

In [75]:
linreg.score(x_test, y_test)

0.5384708385062805

#### What is the r2 measure? is it good, why?

The R2 measure is not good at .53, we would want to get a score closer to 1 for it to be an optimal test.